export type ConvertCase = {
  label: string;
  input: string;
  expectedReadings?: string[];
  expectedHtml?: string;
};

export type BacklogConvertCase = {
  category: string;
  input: string;
  expected: string;
};

export const BACKLOG_CONVERT_CASES: BacklogConvertCase[] = [
  { input: '今日', expected: 'きょう', category: '熟字訓' },
  { input: '明日', expected: 'あした', category: '熟字訓' },
  { input: '一期一会', expected: 'いちごいちえ', category: '熟字訓' },
  { input: '昨日', expected: 'きのう', category: '熟字訓' },
  { input: '大人', expected: 'おとな', category: '熟字訓' },
  { input: '一人', expected: 'ひとり', category: '熟字訓' },
  { input: '二人', expected: 'ふたり', category: '熟字訓' },
  { input: '二十歳', expected: 'はたち', category: '熟字訓' },
  { input: '二十日', expected: 'はつか', category: '熟字訓' },
  { input: 'お母さん', expected: 'おかあさん', category: '熟字訓' },
  { input: 'お父さん', expected: 'おとうさん', category: '熟字訓' },
  { input: '真面目', expected: 'まじめ', category: '熟字訓' },
  { input: '眼鏡', expected: 'めがね', category: '熟字訓' },
  { input: '時計', expected: 'とけい', category: '熟字訓' },
  { input: '土産', expected: 'みやげ', category: '熟字訓' },
  { input: '息子', expected: 'むすこ', category: '常用' },
  { input: '娘', expected: 'むすめ', category: '常用' },
  { input: '上手', expected: 'じょうず', category: '常用' },
  { input: '下手', expected: 'へた', category: '常用' },
  { input: '田舎', expected: 'いなか', category: '常用' },
  { input: '景色', expected: 'けしき', category: '常用' },
  { input: '食べる', expected: 'た', category: '活用-一段' },
  { input: '食べて', expected: 'た', category: '活用-一段' },
  { input: '行きます', expected: 'い', category: '活用-五段' },
  { input: '行った', expected: 'い', category: '活用-五段' },
  { input: '更ける', expected: 'ふ', category: '活用-点号匹配' },
  { input: '更かす', expected: 'ふ', category: '活用-点号匹配' },
  { input: '高い', expected: 'たか', category: '活用-形容词' },
  { input: '高く', expected: 'たか', category: '活用-形容词' },
  { input: '美しく', expected: 'うつく', category: '活用-形容词' },
  { input: '美しい', expected: 'うつく', category: '活用-形容词' },
  { input: '明るい', expected: 'あか', category: '活用-形容词' },
  { input: '開ける', expected: 'あ', category: '活用-成对动词' },
  { input: '閉める', expected: 'し', category: '活用-成对动词' },
  { input: '落ちる', expected: 'お', category: '活用-成对动词' },
  { input: '落とす', expected: 'お', category: '活用-成对动词' },
  { input: '始める', expected: 'はじ', category: '活用' },
  { input: '終わる', expected: 'お', category: '活用' },
  { input: '笑う', expected: 'わら', category: '活用' },
  { input: '怒る', expected: 'おこ', category: '活用' },
  { input: '楽しむ', expected: 'たの', category: '活用' },
  { input: '1本', expected: 'いっぽん', category: '数字变音' },
  { input: '3本', expected: 'さんぼん', category: '数字变音' },
  { input: '6本', expected: 'ろっぽん', category: '数字变音' },
  { input: '8本', expected: 'はっぽん', category: '数字变音' },
  { input: '10本', expected: 'じゅっぽん', category: '数字变音' },
  { input: '1分', expected: 'いっぷん', category: '数字变音' },
  { input: '3分', expected: 'さんぷん', category: '数字变音' },
  { input: '4分', expected: 'よんぷん', category: '数字变音' },
  { input: '1回', expected: 'いっかい', category: '数字变音' },
  { input: '10回', expected: 'じゅっかい', category: '数字变音' },
  { input: '1匹', expected: 'いっぴき', category: '数字变音' },
  { input: '3匹', expected: 'さんびき', category: '数字变音' },
  { input: '1階', expected: 'いっかい', category: '数字变音' },
  { input: '3階', expected: 'さんがい', category: '数字变音' },
  { input: '1册', expected: 'いっさつ', category: '数字变音' },
  { input: '1足', expected: 'いっそく', category: '数字变音' },
  { input: '3足', expected: 'さんぞく', category: '数字变音' },
  { input: '1着', expected: 'いっちゃく', category: '数字变音' },
  { input: '1个', expected: 'いっこ', category: '数字变音' },
  { input: '10个', expected: 'じゅっこ', category: '数字变音' },
  { input: '东京', expected: 'とうきょう', category: '地名' },
  { input: '大阪', expected: 'おおさか', category: '地名' },
  { input: '京都', expected: 'きょうと', category: '地名' },
  { input: '新宿', expected: 'しんじゅく', category: '地名' },
  { input: '渋谷', expected: 'しぶや', category: '地名' },
  { input: '北海道', expected: 'ほっかいどう', category: '地名' },
  { input: '九州', expected: 'きゅうしゅう', category: '地名' },
  { input: '佐藤', expected: 'さとう', category: '姓氏' },
  { input: '鈴木', expected: 'すずき', category: '姓氏' },
  { input: '高橋', expected: 'たかはし', category: '姓氏' },
  { input: '渡辺', expected: 'わたなべ', category: '姓氏' },
  { input: '伊藤', expected: 'いとう', category: '姓氏' },
  { input: '山本', expected: 'やまもと', category: '姓氏' },
  { input: '中村', expected: 'なかむら', category: '姓氏' },
  { input: '小林', expected: 'こばやし', category: '姓氏' },
  { input: '鼻血', expected: 'はなぢ', category: '连浊' },
  { input: '株式会社', expected: 'かぶしきがいしゃ', category: '连浊' },
  { input: '三日月', expected: 'みかづき', category: '连浊' },
  { input: '手紙', expected: 'てがみ', category: '连浊' },
  { input: '青空', expected: 'あおぞら', category: '连浊' },
  { input: '自分', expected: 'じぶん', category: '常用' },
  { input: '近道', expected: 'ちかみち', category: '连浊' },
  { input: '神棚', expected: 'かみだな', category: '连浊' },
  { input: '人込み', expected: 'ひとごみ', category: '连浊' },
  { input: '本箱', expected: 'ほんばこ', category: '连浊' },
  { input: '花火', expected: 'はなび', category: '连浊' },
  { input: '足首', expected: 'あしくび', category: '连浊' },
  { input: '裏切る', expected: 'うらぎる', category: '连浊' },
  { input: '目印', expected: 'めじるし', category: '连浊' },
  { input: '長靴', expected: 'ながぐつ', category: '连浊' },
  { input: '開発', expected: 'かいはつ', category: 'IT术语' },
  { input: '修正', expected: 'しゅうせい', category: 'IT术语' },
  { input: '機能', expected: 'きのう', category: 'IT术语' },
  { input: '変数', expected: 'へんすう', category: 'IT术语' },
  { input: '同期', expected: 'どうき', category: 'IT术语' },
  { input: '環境', expected: 'かんきょう', category: 'IT术语' },
  { input: '接続', expected: 'せつぞく', category: 'IT术语' },
  { input: '保存', expected: 'ほぞん', category: 'IT术语' },
  { input: '更新', expected: 'こうしん', category: 'IT术语' },
  { input: '設定', expected: 'せってい', category: 'IT术语' },
];
export const ACTIVE_CONVERT_CASES: ConvertCase[] = [
  { label: '熟字訓 - 誕生日', input: '誕生日', expectedReadings: ['たんじょうび'] },
  { label: '送假名 - 懐かしい', input: '懐かしい', expectedReadings: ['なつかしい'] },
  { label: '数字助数词 - 5歳', input: '5歳', expectedReadings: ['ごさい'] },
  { label: '数字助数词 - 3本', input: '3本', expectedReadings: ['さんぼん'] },
  { label: '数字助数词 - 1300台', input: '1300台', expectedReadings: ['せんさんびゃくだい'] },
  { label: '人名 - 田中', input: '田中', expectedReadings: ['たなか'] },
  { label: 'IT术语 - 接続', input: '接続', expectedReadings: ['せつぞく'] },
  { label: '纯假名直通', input: 'こんにちは', expectedHtml: 'こんにちは' },
];
